const API_BASE = ((location.hostname === "127.0.0.1" || location.hostname === "localhost") && location.port === "5001") ? "http://127.0.0.1:5002/api/bihar" : "/api/bihar";
const $ = id => document.getElementById(id);
const el = {
  ring: $("apiRing"), status: $("apiStatusText"), meta: $("fetchMeta"), alert: $("alertStrip"), alertTitle: $("alertTitle"), alertMsg: $("alertMessage"), alertTime: $("alertTime"),
  search: $("stationSearch"), district: $("districtSelect"), level: $("statusSelect"), refresh: $("refreshButton"), count: $("observationCount"), danger: $("dangerCount"), warning: $("warningCount"), rising: $("risingCount"), table: $("riverTableBody"),
  detailStation: $("detailStation"), detailRiver: $("detailRiver"), detailStatus: $("detailStatus"), detailLevel: $("detailLevel"), detailWarning: $("detailWarning"), detailDanger: $("detailDanger"), detailHfl: $("detailHfl"), detailChange: $("detailChange"), detailTrend: $("detailTrend"), detailObserved: $("detailObserved"), warningMarker: $("warningMarker"), dangerMarker: $("dangerMarker"), levelMarker: $("levelMarker"), network: $("networkState"), error: $("errorCard"), errorText: $("errorMessage")
};
let records = [], selectedDistrict = "", selectedLevel = "", selectedStation = null;
const norm = v => String(v ?? "").trim().toLowerCase();
const fmt = v => Number.isFinite(Number(v)) ? Number(v).toFixed(2) : "—";
const observed = v => { if (!v) return "—"; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleString("en-IN", {day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false}); };
const safe = v => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function levelStatus(r){ const l=Number(r.water_level_m), w=Number(r.warning_level_m), d=Number(r.danger_level_m); return Number.isFinite(l)&&Number.isFinite(d)&&l>=d?"danger":Number.isFinite(l)&&Number.isFinite(w)&&l>=w?"warning":"normal"; }
function statusLabel(s){ return s === "danger" ? "DANGER" : s === "warning" ? "WARNING" : "NORMAL"; }
function apiState(ok,text){ el.ring.classList.toggle("online",ok); el.ring.classList.toggle("offline",!ok); el.status.textContent=text; el.network.textContent=ok?"NETWORK ONLINE":"NETWORK OFFLINE"; }
function filtered(){ const q=norm(el.search.value); return records.filter(r=>(!selectedDistrict||norm(r.district)===norm(selectedDistrict))&&(!selectedLevel||levelStatus(r)===selectedLevel)&&(!q||[r.station,r.river,r.district].some(v=>norm(v).includes(q)))); }
function districts(){ const list=[...new Set(records.map(r=>r.district).filter(Boolean))].sort((a,b)=>a.localeCompare(b)); el.district.innerHTML='<option value="">All Bihar</option>'+list.map(d=>`<option value="${safe(d)}">${safe(d)}</option>`).join(""); el.district.value=selectedDistrict; }
function metrics(list){ el.count.textContent=list.length; el.danger.textContent=list.filter(r=>levelStatus(r)==="danger").length; el.warning.textContent=list.filter(r=>levelStatus(r)==="warning").length; el.rising.textContent=list.filter(r=>norm(r.trend)==="rising").length; }
function alertState(){ const d=records.filter(r=>levelStatus(r)==="danger"), w=records.filter(r=>levelStatus(r)==="warning"), rising=records.filter(r=>norm(r.trend)==="rising"); el.alert.classList.remove("danger","warning","normal"); if(d.length){el.alert.classList.add("danger");el.alertTitle.textContent=`${d.length} STATION${d.length>1?"S":""} AT / ABOVE DANGER LEVEL`;el.alertMsg.textContent=`${d[0].station} is currently at ${fmt(d[0].water_level_m)} m.`;}else if(w.length){el.alert.classList.add("warning");el.alertTitle.textContent=`${w.length} STATION${w.length>1?"S":""} AT / ABOVE WARNING LEVEL`;el.alertMsg.textContent=`${w[0].station} is currently at ${fmt(w[0].water_level_m)} m.`;}else{el.alert.classList.add("normal");el.alertTitle.textContent="NO STATION ABOVE WARNING LEVEL";el.alertMsg.textContent=rising.length?`${rising.length} station${rising.length>1?"s are":" is"} currently rising.`:"All monitored stations are below warning level.";}el.alertTime.textContent=new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false});}
function render(){ const list=filtered(); metrics(list); if(!list.length){el.table.innerHTML='<tr><td colspan="6" class="empty-state">No stations match the current filters.</td></tr>';return;} el.table.innerHTML=list.map((r,i)=>{const s=levelStatus(r),t=norm(r.trend)||"unknown",sel=selectedStation&&selectedStation.station===r.station&&selectedStation.district===r.district;return `<tr class="station-row ${sel?"selected":""}" data-i="${i}"><td><button class="station-button" type="button"><strong>${safe(r.station)}</strong><span>${safe(r.river)}</span></button></td><td>${safe(r.district)}</td><td><strong class="level-value ${s}">${fmt(r.water_level_m)} m</strong></td><td><span class="threshold-badge ${s}">${statusLabel(s)}</span> <small>${fmt(s==="danger"?r.danger_level_m:r.warning_level_m)} m</small></td><td><span class="trend ${safe(t)}"><i></i>${safe(r.trend||"Unknown")}</span></td><td>${observed(r.observed_at)}</td></tr>`;}).join(""); el.table.querySelectorAll(".station-row").forEach((row,i)=>row.addEventListener("click",()=>select(list[i]))); }
function select(r){ selectedStation=r; const s=levelStatus(r); el.detailStation.textContent=r.station||"Unknown station";el.detailRiver.textContent=`${r.river||"River"} • ${r.district||"Bihar"}`;el.detailStatus.textContent=statusLabel(s);el.detailStatus.className=`detail-status ${s}`;el.detailLevel.textContent=fmt(r.water_level_m);el.detailWarning.textContent=`${fmt(r.warning_level_m)} m`;el.detailDanger.textContent=`${fmt(r.danger_level_m)} m`;el.detailHfl.textContent=`${fmt(r.hfl_m)} m`;const change=Number(r.water_level_m)-Number(r.water_level_1h_before_m);el.detailChange.textContent=Number.isFinite(change)?`${change>=0?"+":""}${change.toFixed(2)} m`:"—";el.detailTrend.textContent=r.trend||"—";el.detailObserved.textContent=observed(r.observed_at);const w=Number(r.warning_level_m),d=Number(r.danger_level_m),h=Number(r.hfl_m),l=Number(r.water_level_m),max=Number.isFinite(h)&&h>0?h:Math.max(w,d,l,1),pos=v=>`${Math.max(0,Math.min(100,v/max*100))}%`;el.warningMarker.style.left=Number.isFinite(w)?pos(w):"0%";el.dangerMarker.style.left=Number.isFinite(d)?pos(d):"0%";el.levelMarker.style.left=Number.isFinite(l)?pos(l):"0%";el.levelMarker.className=`level-marker ${s}`;render(); }
async function load(force=false){ el.error.hidden=true;apiState(false,"LOADING");el.refresh.disabled=true;el.table.innerHTML='<tr><td colspan="6" class="empty-state">Loading river intelligence...</td></tr>';try{const q=force?"?refresh=true":"",res=await fetch(`${API_BASE}/live-rivers${q}`,{headers:{Accept:"application/json"}}),p=await res.json();if(!res.ok||!p.success)throw new Error(p.error||`API request failed (${res.status})`);records=Array.isArray(p.records)?p.records:[];districts();const mode=p.source_mode==="fallback_snapshot"?"FMISC snapshot fallback":p.cached?"cached":"fresh";const when=p.fetched_at?observed(p.fetched_at):"unknown";el.meta.textContent=`${mode} • fetched ${when} • ${p.count??records.length} stations`;alertState();render();if(!selectedStation&&records.length)select(records[0]);apiState(true,p.source_mode==="fallback_snapshot"?"API ONLINE · SNAPSHOT":"API ONLINE");}catch(e){records=[];metrics([]);el.table.innerHTML='<tr><td colspan="6" class="empty-state">Live observations could not be loaded.</td></tr>';el.meta.textContent="Live data unavailable";el.error.hidden=false;el.errorText.textContent=e instanceof Error?e.message:"Unable to fetch live Bihar river data.";apiState(false,"API OFFLINE");}finally{el.refresh.disabled=false;}}
el.search.addEventListener("input",render);el.district.addEventListener("change",e=>{selectedDistrict=e.target.value;render();});el.level.addEventListener("change",e=>{selectedLevel=e.target.value;render();});el.refresh.addEventListener("click",()=>load(true));load();setInterval(()=>load(false),300000);