const API_BASE = ((location.hostname === "127.0.0.1" || location.hostname === "localhost") && location.port === "5001") ? "http://127.0.0.1:5002/api/bihar" : "/api/bihar";
const $ = id => document.getElementById(id);
const el = {
  ring: $("apiRing"), status: $("apiStatusText"), meta: $("fetchMeta"), alert: $("alertStrip"), alertTitle: $("alertTitle"), alertMsg: $("alertMessage"), alertTime: $("alertTime"),
  search: $("stationSearch"), district: $("districtSelect"), level: $("statusSelect"), refresh: $("refreshButton"), count: $("observationCount"), danger: $("dangerCount"), warning: $("warningCount"), rising: $("risingCount"), table: $("riverTableBody"),
  detailStation: $("detailStation"), detailRiver: $("detailRiver"), detailStatus: $("detailStatus"), detailLevel: $("detailLevel"), detailWarning: $("detailWarning"), detailDanger: $("detailDanger"), detailHfl: $("detailHfl"), detailChange: $("detailChange"), detailTrend: $("detailTrend"), detailObserved: $("detailObserved"), warningMarker: $("warningMarker"), dangerMarker: $("dangerMarker"), levelMarker: $("levelMarker"), network: $("networkState"), error: $("errorCard"), errorText: $("errorMessage"),
  riskMetric: $("riskEngineMetric"), riskMetricState: $("riskEngineState"), riskBadge: $("riskEngineBadge"), riskScore: $("riskEngineScore"), riskLabel: $("riskEngineLabel"), riskProgress: $("riskProgress"), riskCopy: $("riskEngineCopy"), riskFactLevel: $("riskFactLevel"), riskFactRise: $("riskFactRise"), riskFactState: $("riskFactState"),
  inundBadge: $("inundationBadge"), inundScore: $("inundationScore"), inundLabel: $("inundationLabel"), inundProgress: $("inundationProgress"), inundCopy: $("inundationCopy"), inundGrid: $("inundationGrid"), inundMapLabel: $("inundationMapLabel"), inundExtent: $("inundationFactExtent"), inundDepth: $("inundationFactDepth"), inundConfidence: $("inundationFactConfidence"),
  map: $("biharMap"), mapStatus: $("mapStatus")
};
let records = [], selectedDistrict = "", selectedLevel = "", selectedStation = null, map = null, mapLayer = null;
const norm = v => String(v ?? "").trim().toLowerCase();
const fmt = v => Number.isFinite(Number(v)) ? Number(v).toFixed(2) : "—";
const observed = v => { if (!v) return "—"; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleString("en-IN", {day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false}); };
const safe = v => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function levelStatus(r){ const l=Number(r.water_level_m), w=Number(r.warning_level_m), d=Number(r.danger_level_m); return Number.isFinite(l)&&Number.isFinite(d)&&l>=d?"danger":Number.isFinite(l)&&Number.isFinite(w)&&l>=w?"warning":"normal"; }
function statusLabel(s){ return s === "danger" ? "DANGER" : s === "warning" ? "WARNING" : "NORMAL"; }
function apiState(ok,text){ el.ring.classList.toggle("online",ok); el.ring.classList.toggle("offline",!ok); el.status.textContent=text; el.network.textContent=ok?"NETWORK ONLINE":"NETWORK OFFLINE"; }
function filtered(){ const q=norm(el.search.value); return records.filter(r=>(!selectedDistrict||norm(r.district)===norm(selectedDistrict))&&(!selectedLevel||levelStatus(r)===selectedLevel)&&(!q||[r.station,r.river,r.district].some(v=>norm(v).includes(q)))); }
function districts(){ const list=[...new Set(records.map(r=>r.district).filter(Boolean))].sort((a,b)=>a.localeCompare(b)); el.district.innerHTML='<option value="">All Bihar</option>'+list.map(d=>`<option value="${safe(d)}">${safe(d)}</option>`).join(""); el.district.value=selectedDistrict; }
function metrics(list){ el.count.textContent=list.length; el.danger.textContent=list.filter(r=>levelStatus(r)==="danger").length; el.warning.textContent=list.filter(r=>levelStatus(r)==="warning").length; el.rising.textContent=list.filter(r=>norm(r.trend)==="rising").length; }
function alertState(){ const d=records.filter(r=>levelStatus(r)==="danger"), w=records.filter(r=>levelStatus(r)==="warning"), rising=records.filter(r=>norm(r.trend)==="rising"); el.alert.classList.remove("danger","warning","normal"); if(d.length){el.alert.classList.add("danger");el.alertTitle.textContent=`${d.length} STATION${d.length>1?"S":""} AT / ABOVE DANGER LEVEL`;el.alertMsg.textContent=`${d[0].station} is currently at ${fmt(d[0].water_level_m)} m.`;}else if(w.length){el.alert.classList.add("warning");el.alertTitle.textContent=`${w.length} STATION${w.length>1?"S":""} AT / ABOVE WARNING LEVEL`;el.alertMsg.textContent=`${w[0].station} is currently at ${fmt(w[0].water_level_m)} m.`;}else{el.alert.classList.add("normal");el.alertTitle.textContent="NO STATION ABOVE WARNING LEVEL";el.alertMsg.textContent=rising.length?`${rising.length} station${rising.length>1?"s are":" is"} currently rising.`:"All monitored stations are below warning level.";}el.alertTime.textContent=new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false});}
function render(){ const list=filtered(); metrics(list); if(!list.length){el.table.innerHTML='<tr><td colspan="6" class="empty-state">No stations match the current filters.</td></tr>';return;} el.table.innerHTML=list.map((r,i)=>{const s=levelStatus(r),t=norm(r.trend)||"unknown",sel=selectedStation&&selectedStation.station===r.station&&selectedStation.district===r.district;return `<tr class="station-row ${sel?"selected":""}" data-i="${i}"><td><button class="station-button" type="button"><strong>${safe(r.station)}</strong><span>${safe(r.river)}</span></button></td><td>${safe(r.district)}</td><td><strong class="level-value ${s}">${fmt(r.water_level_m)} m</strong></td><td><span class="threshold-badge ${s}">${statusLabel(s)}</span> <small>${fmt(s==="danger"?r.danger_level_m:r.warning_level_m)} m</small></td><td><span class="trend ${safe(t)}"><i></i>${safe(r.trend||"Unknown")}</span></td><td>${observed(r.observed_at)}</td></tr>`;}).join(""); el.table.querySelectorAll(".station-row").forEach((row,i)=>row.addEventListener("click",()=>select(list[i]))); updateMap(list); }
function resetEnginePanels(){ el.riskMetric.textContent="—"; el.riskMetricState.textContent=selectedStation?"waiting for model":"select a station"; el.riskBadge.textContent="LOADING"; el.riskBadge.className="engine-state"; el.riskScore.textContent="—%"; el.riskLabel.textContent="NO PREDICTION"; el.riskLabel.className="engine-state"; el.riskProgress.style.width="0%"; el.riskCopy.textContent="Loading the 24-hour flood-risk engine..."; el.inundBadge.textContent="LOADING"; el.inundBadge.className="engine-state"; el.inundScore.textContent="—"; el.inundLabel.textContent="NO EXTENT"; el.inundLabel.className="engine-state"; el.inundProgress.style.width="0%"; el.inundCopy.textContent="Loading the 24-hour inundation layer..."; el.inundExtent.textContent="—"; el.inundDepth.textContent="—"; el.inundConfidence.textContent="—"; el.inundMapLabel.textContent="WAITING FOR MODEL"; el.inundGrid.innerHTML=""; }
function riskFromApi(data,r){ const probability=Number(data?.probability), label=String(data?.risk_level||data?.risk||"").toUpperCase(); const available=Boolean(data?.available)&&Number.isFinite(probability); if(!available){el.riskMetric.textContent="—";el.riskMetricState.textContent=data?.method?`baseline: ${data.method.replaceAll("_"," ")}`:"not available";el.riskBadge.textContent=data?.method==="live_observation_baseline"?"BASELINE":"UNAVAILABLE";el.riskBadge.className=`engine-state ${data?.method==="live_observation_baseline"?"advisory":""}`;el.riskScore.textContent="—%";el.riskLabel.textContent=label||"NO PREDICTION";el.riskLabel.className="engine-state";el.riskProgress.style.width="0%";el.riskCopy.textContent=data?.message||"Flood probability is not available for this station.";return;} const pct=Math.max(0,Math.min(100,probability*100));el.riskMetric.textContent=`${pct.toFixed(0)}%`;el.riskMetricState.textContent=data.calibrated===false?"live baseline • not calibrated":"model prediction";el.riskBadge.textContent=data.calibrated===false?"BASELINE":"MODEL OUTPUT";el.riskBadge.className=`engine-state ${data.calibrated===false?"advisory":"live"}`;el.riskScore.textContent=`${pct.toFixed(0)}%`;el.riskLabel.textContent=label||"PREDICTION";el.riskLabel.className=`engine-state ${label.includes("HIGH")?"advisory":"live"}`;el.riskProgress.style.width=`${pct}%`;el.riskCopy.textContent=data.message||"24-hour flood-risk estimate returned from the live Bihar pipeline."; }
function inundationFromApi(data){ const extent=Number(data?.extent_percent),depth=Number(data?.depth_m),confidence=Number(data?.confidence); const available=Boolean(data?.available)&&Number.isFinite(extent)&&Number.isFinite(depth); if(!available){el.inundBadge.textContent="BASELINE";el.inundBadge.className="engine-state advisory";el.inundScore.textContent="—";el.inundLabel.textContent="NO VALIDATED EXTENT";el.inundLabel.className="engine-state advisory";el.inundProgress.style.width="0%";el.inundExtent.textContent="—";el.inundDepth.textContent="—";el.inundConfidence.textContent="—";el.inundCopy.textContent=data?.message||"A validated spatial inundation model requires terrain and flood-extent data.";el.inundMapLabel.textContent="NO VALIDATED MAP";return;}el.inundBadge.textContent=data.physical_model===false?"SPATIAL PROXY":"MODEL OUTPUT";el.inundBadge.className=`engine-state ${data.physical_model===false?"advisory":"live"}`;el.inundScore.textContent=`${extent.toFixed(1)}%`;el.inundLabel.textContent=data.physical_model===false?"PROXY EXTENT":"PREDICTED EXTENT";el.inundLabel.className=`engine-state ${data.physical_model===false?"advisory":"live"}`;el.inundProgress.style.width=`${Math.max(0,Math.min(100,extent))}%`;el.inundExtent.textContent=`${extent.toFixed(1)}%`;el.inundDepth.textContent=`${depth.toFixed(2)} m`;el.inundConfidence.textContent=Number.isFinite(confidence)?`${(confidence<=1?confidence*100:confidence).toFixed(0)}%`:"—";el.inundCopy.textContent=data.message||"24-hour inundation output returned for the selected station.";el.inundMapLabel.textContent=data.physical_model===false?"PROXY • NOT A FLOOD MAP":"MODEL OUTPUT"; }
async function fetchEngine(path,r){ try{const params=new URLSearchParams({station:r.station||"",district:r.district||"",river:r.river||""});const res=await fetch(`${API_BASE}/${path}?${params}`,{headers:{Accept:"application/json"}});const p=await res.json().catch(()=>null);if(!res.ok)return p?{...p,available:false}:null;return p;}catch{return null;} }
async function loadEngines(r){ resetEnginePanels(); if(!r)return; el.riskFactLevel.textContent=`${fmt(r.water_level_m)} m`;const change=Number(r.water_level_m)-Number(r.water_level_1h_before_m);el.riskFactRise.textContent=Number.isFinite(change)?`${change>=0?"+":""}${change.toFixed(2)} m`:`${String(r.trend||"—")}`;el.riskFactState.textContent=statusLabel(levelStatus(r));
 const [risk,inund]=await Promise.all([fetchEngine("risk",r),fetchEngine("inundation",r)]);
 if(risk) riskFromApi(risk,r); else {el.riskBadge.textContent="OFFLINE";el.riskBadge.className="engine-state advisory";el.riskLabel.textContent="UNAVAILABLE";el.riskCopy.textContent="Risk engine request failed.";}
 if(inund) inundationFromApi(inund); else {el.inundBadge.textContent="OFFLINE";el.inundBadge.className="engine-state advisory";el.inundLabel.textContent="UNAVAILABLE";el.inundCopy.textContent="Inundation engine request failed.";}
}
function initMap(){ if(!el.map||!window.L)return; map=L.map(el.map,{zoomControl:true,scrollWheelZoom:true}).setView([25.0961,85.3131],7); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:"&copy; OpenStreetMap contributors"}).addTo(map); }
function updateMap(list){ if(!map||!window.L)return; if(mapLayer){map.removeLayer(mapLayer);mapLayer=null;} const markers=[]; list.forEach(r=>{const lat=Number(r.latitude),lon=Number(r.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))return;const s=levelStatus(r);const color=s==="danger"?"#ff5d68":s==="warning"?"#f4b740":"#38d39f";const marker=L.circleMarker([lat,lon],{radius:s==="danger"?9:7,color,fillColor:color,fillOpacity:.8,weight:2});marker.bindPopup(`<strong>${safe(r.station)}</strong><br>${safe(r.river)} • ${safe(r.district)}<br>Level: ${fmt(r.water_level_m)} m<br>Status: ${statusLabel(s)}<br><small>${observed(r.observed_at)}</small>`);marker.on("click",()=>select(r));markers.push(marker);}); if(markers.length){mapLayer=L.layerGroup(markers).addTo(map);el.mapStatus.textContent=`${markers.length} mapped stations`; } else el.mapStatus.textContent="Coordinates unavailable"; }
function select(r){ selectedStation=r; const s=levelStatus(r); el.detailStation.textContent=r.station||"Unknown station";el.detailRiver.textContent=`${r.river||"River"} • ${r.district||"Bihar"}`;el.detailStatus.textContent=statusLabel(s);el.detailStatus.className=`detail-status ${s}`;el.detailLevel.textContent=fmt(r.water_level_m);el.detailWarning.textContent=`${fmt(r.warning_level_m)} m`;el.detailDanger.textContent=`${fmt(r.danger_level_m)} m`;el.detailHfl.textContent=`${fmt(r.hfl_m)} m`;const change=Number(r.water_level_m)-Number(r.water_level_1h_before_m);el.detailChange.textContent=Number.isFinite(change)?`${change>=0?"+":""}${change.toFixed(2)} m`:"—";el.detailTrend.textContent=r.trend||"—";el.detailObserved.textContent=observed(r.observed_at);const w=Number(r.warning_level_m),d=Number(r.danger_level_m),h=Number(r.hfl_m),l=Number(r.water_level_m),max=Number.isFinite(h)&&h>0?h:Math.max(w,d,l,1),pos=v=>`${Math.max(0,Math.min(100,v/max*100))}%`;el.warningMarker.style.left=Number.isFinite(w)?pos(w):"0%";el.dangerMarker.style.left=Number.isFinite(d)?pos(d):"0%";el.levelMarker.style.left=Number.isFinite(l)?pos(l):"0%";el.levelMarker.className=`level-marker ${s}`;render();loadEngines(r); }
async function load(force=false){ el.error.hidden=true;apiState(false,"LOADING");el.refresh.disabled=true;el.table.innerHTML='<tr><td colspan="6" class="empty-state">Loading river intelligence...</td></tr>';try{const q=force?"?refresh=true":"",res=await fetch(`${API_BASE}/live-rivers${q}`,{headers:{Accept:"application/json"}}),p=await res.json();if(!res.ok||!p.success)throw new Error(p.error||`API request failed (${res.status})`);records=Array.isArray(p.records)?p.records:[];districts();const mode=p.source_mode==="neon_live_snapshot"?"LIVE • Neon synced":p.cached?"cached":"fresh";const when=p.fetched_at?observed(p.fetched_at):"unknown";el.meta.textContent=`${mode} • last sync ${when} • ${p.count??records.length} stations`;alertState();render();if(!selectedStation&&records.length)select(records[0]);else if(selectedStation){const current=records.find(r=>r.station===selectedStation.station&&r.district===selectedStation.district);if(current)select(current);}apiState(true,p.source_mode==="neon_live_snapshot"?"API ONLINE · LIVE SYNC":"API ONLINE");}catch(e){records=[];metrics([]);el.table.innerHTML='<tr><td colspan="6" class="empty-state">Live observations could not be loaded.</td></tr>';el.meta.textContent="Live data unavailable";el.error.hidden=false;el.errorText.textContent=e instanceof Error?e.message:"Unable to fetch live Bihar river data.";apiState(false,"API OFFLINE");resetEnginePanels();}finally{el.refresh.disabled=false;}}
el.search.addEventListener("input",render);el.district.addEventListener("change",e=>{selectedDistrict=e.target.value;render();});el.level.addEventListener("change",e=>{selectedLevel=e.target.value;render();});el.refresh.addEventListener("click",()=>load(true));initMap();load();setInterval(()=>load(false),60000);