const API_BASE = ((location.hostname === "127.0.0.1" || location.hostname === "localhost") && location.port === "5001") ? "http://127.0.0.1:5002/api/bihar" : "/api/bihar";
const $ = id => document.getElementById(id);
const el = {
  ring: $("apiRing"), status: $("apiStatusText"), meta: $("fetchMeta"), alert: $("alertStrip"), alertTitle: $("alertTitle"), alertMsg: $("alertMessage"), alertTime: $("alertTime"),
  search: $("stationSearch"), district: $("districtSelect"), level: $("statusSelect"), refresh: $("refreshButton"), count: $("observationCount"), danger: $("dangerCount"), warning: $("warningCount"), rising: $("risingCount"), table: $("riverTableBody"),
  detailStation: $("detailStation"), detailRiver: $("detailRiver"), detailStatus: $("detailStatus"), detailLevel: $("detailLevel"), detailWarning: $("detailWarning"), detailDanger: $("detailDanger"), detailHfl: $("detailHfl"), detailChange: $("detailChange"), detailTrend: $("detailTrend"), detailObserved: $("detailObserved"), warningMarker: $("warningMarker"), dangerMarker: $("dangerMarker"), levelMarker: $("levelMarker"), network: $("networkState"), error: $("errorCard"), errorText: $("errorMessage"),
  riskMetric: $("riskEngineMetric"), riskMetricState: $("riskEngineState"), riskBadge: $("riskEngineBadge"), riskScore: $("riskEngineScore"), riskLabel: $("riskEngineLabel"), riskProgress: $("riskProgress"), riskCopy: $("riskEngineCopy"), riskFactLevel: $("riskFactLevel"), riskFactRise: $("riskFactRise"), riskFactState: $("riskFactState"),
  inundBadge: $("inundationBadge"), inundScore: $("inundationScore"), inundLabel: $("inundationLabel"), inundProgress: $("inundationProgress"), inundCopy: $("inundationCopy"), inundGrid: $("inundationGrid"), inundMapLabel: $("inundationMapLabel"), inundExtent: $("inundationFactExtent"), inundDepth: $("inundationFactDepth"), inundConfidence: $("inundationFactConfidence")
};
let records = [], selectedDistrict = "", selectedLevel = "", selectedStation = null;
const norm = v => String(v ?? "").trim().toLowerCase();
const fmt = v => Number.isFinite(Number(v)) ? Number(v).toFixed(2) : "—";
const observed = v => { if (!v) return "—"; const d = new Date(v); return Number.isNaN(d.getTime()) ? String(v) : d.toLocaleString("en-IN", {day:"2-digit",month:"short",hour:"2-digit",minute:"2-digit",hour12:false}); };
const safe = v => String(v ?? "").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");
function levelStatus(r){ const l=Number(r.water_level_m), w=Number(r.warning_level_m), d=Number(r.danger_level_m); return Number.isFinite(l)&&Number.isFinite(d)&&l>=d?"danger":Number.isFinite(l)&&Number.isFinite(w)&&l>=w?"warning":"normal"; }
function statusLabel(s){ return s === "danger" ? "DANGER" : s === "warning" ? "WARNING" : "NORMAL"; }
function apiState(ok,text){ el.ring.classList.toggle("online",ok); el.ring.classList.toggle("offline",!ok); el.status.textContent=text; el.network.textContent=ok?"NETWORK ONLINE":"NETWORK OFFLINE"; }
function filtered(){ const q=norm(el.search.value); return records.filter(r=>(!selectedDistrict||norm(r.district)===norm(selectedDistrict))&&(!selectedLevel||levelStatus(r)===selectedLevel)&&(!q||[r.station,r.river,r.district].some(v=>norm(v).includes(q)))); }
function districts(){ const list=[...new Set(records.map(r=>r.district).filter(Boolean))].sort((a,b)=>a.localeCompare(b)); el.district.innerHTML='<option value="">All Bihar</option>'+list.map(d=>`<option value="${safe(d)}">${safe(d)}</option>`).join(""); el.district.value=selectedDistrict; }
function metrics(list){ el.count.textContent=list.length; el.danger.textContent=list.filter(r=>levelStatus(r)==="danger").length; el.warning.textContent=list.filter(r=>levelStatus(r)==="warning").length; el.rising.textContent=list.filter(r=>norm(r.trend)==="rising").length; }
function alertState(){ const d=records.filter(r=>levelStatus(r)==="danger"), w=records.filter(r=>levelStatus(r)==="warning"), rising=records.filter(r=>norm(r.trend)==="rising"); el.alert.classList.remove("danger","warning","normal"); if(d.length){el.alert.classList.add("danger");el.alertTitle.textContent=`${d.length} STATION${d.length>1?"S":""} AT / ABOVE DANGER LEVEL`;el.alertMsg.textContent=`${d[0].station} is currently at ${fmt(d[0].water_level_m)} m.`;}else if(w.length){el.alert.classList.add("warning");el.alertTitle.textContent=`${w.length} STATION${w.length>1?"S":""} AT / ABOVE WARNING LEVEL`;el.alertMsg.textContent=`${w[0].station} is currently at ${fmt(w[0].water_level_m)} m.`;}else{el.alert.classList.add("normal");el.alertTitle.textContent="NO STATION ABOVE WARNING LEVEL";el.alertMsg.textContent=rising.length?`${rising.length} station${rising.length>1?"s are":" is"} currently rising.`:"All monitored stations are below warning level.";}el.alertTime.textContent=new Date().toLocaleTimeString("en-IN",{hour:"2-digit",minute:"2-digit",hour12:false});}
function render(){ const list=filtered(); metrics(list); if(!list.length){el.table.innerHTML='<tr><td colspan="6" class="empty-state">No stations match the current filters.</td></tr>';return;} el.table.innerHTML=list.map((r,i)=>{const s=levelStatus(r),t=norm(r.trend)||"unknown",sel=selectedStation&&selectedStation.station===r.station&&selectedStation.district===r.district;return `<tr class="station-row ${sel?"selected":""}" data-i="${i}"><td><button class="station-button" type="button"><strong>${safe(r.station)}</strong><span>${safe(r.river)}</span></button></td><td>${safe(r.district)}</td><td><strong class="level-value ${s}">${fmt(r.water_level_m)} m</strong></td><td><span class="threshold-badge ${s}">${statusLabel(s)}</span> <small>${fmt(s==="danger"?r.danger_level_m:r.warning_level_m)} m</small></td><td><span class="trend ${safe(t)}"><i></i>${safe(r.trend||"Unknown")}</span></td><td>${observed(r.observed_at)}</td></tr>`;}).join(""); el.table.querySelectorAll(".station-row").forEach((row,i)=>row.addEventListener("click",()=>select(list[i]))); }
function resetEnginePanels(){
  el.riskMetric.textContent="—"; el.riskMetricState.textContent=selectedStation?"API response not available":"select a station"; el.riskBadge.textContent="AWAITING INPUT"; el.riskBadge.className="engine-state"; el.riskScore.textContent="—%"; el.riskLabel.textContent="NO PREDICTION"; el.riskLabel.className="engine-state"; el.riskProgress.style.width="0%"; el.riskCopy.textContent="This panel is reserved for the Bihar flood-probability engine. It must use validated predictive inputs rather than treating a threshold breach as a probability.";
  el.inundBadge.textContent="AWAITING DATA"; el.inundBadge.className="engine-state"; el.inundScore.textContent="—"; el.inundLabel.textContent="NO EXTENT"; el.inundLabel.className="engine-state"; el.inundProgress.style.width="0%"; el.inundCopy.textContent="The inundation engine needs terrain, hydrology and flood-extent inputs. The interface does not infer an inundation extent from a threshold breach."; el.inundExtent.textContent="—"; el.inundDepth.textContent="—"; el.inundConfidence.textContent="—"; el.inundMapLabel.textContent="NO MODEL OUTPUT"; el.inundGrid.innerHTML="";
}
function riskFromApi(data,r){
  const result=data?.risk ?? data?.prediction ?? data?.result ?? null;
  const probability=Number(data?.probability ?? data?.flood_probability ?? data?.risk_probability ?? result?.probability);
  const label=String(data?.risk_level ?? data?.risk ?? result?.risk_level ?? result?.label ?? "").toUpperCase();
  if(!Number.isFinite(probability) && !label) return false;
  const pct=Number.isFinite(probability)?Math.max(0,Math.min(100,probability*100)):NaN;
  el.riskMetric.textContent=Number.isFinite(pct)?`${pct.toFixed(0)}%`:label; el.riskMetricState.textContent="API prediction"; el.riskBadge.textContent="MODEL OUTPUT"; el.riskBadge.className="engine-state live"; el.riskScore.textContent=Number.isFinite(pct)?`${pct.toFixed(0)}%`:"—"; el.riskLabel.textContent=label||"PREDICTION"; el.riskLabel.className=`engine-state ${label.includes("HIGH")?"advisory":"live"}`; el.riskProgress.style.width=Number.isFinite(pct)?`${pct}%`:"0%"; el.riskCopy.textContent=data?.warning||data?.message||"Flood-risk model output returned for the selected station."; return true;
}
function inundationFromApi(data){
  const extent=Number(data?.extent_percent ?? data?.affected_area_percent ?? data?.inundation_percent ?? data?.extent);
  const depth=Number(data?.depth_m ?? data?.max_depth_m ?? data?.predicted_depth_m);
  const confidence=Number(data?.confidence ?? data?.confidence_score);
  const has=Number.isFinite(extent)||Number.isFinite(depth)||Number.isFinite(confidence)||data?.map_url||data?.geojson;
  if(!has) return false;
  el.inundBadge.textContent="MODEL OUTPUT"; el.inundBadge.className="engine-state live"; el.inundScore.textContent=Number.isFinite(extent)?`${extent.toFixed(1)}%`:Number.isFinite(depth)?`${depth.toFixed(2)} m`:"READY"; el.inundLabel.textContent="PREDICTED EXTENT"; el.inundLabel.className="engine-state live"; el.inundProgress.style.width=Number.isFinite(extent)?`${Math.max(0,Math.min(100,extent))}%`:"0%"; el.inundExtent.textContent=Number.isFinite(extent)?`${extent.toFixed(1)}%`:"—"; el.inundDepth.textContent=Number.isFinite(depth)?`${depth.toFixed(2)} m`:"—"; el.inundConfidence.textContent=Number.isFinite(confidence)?`${(confidence<=1?confidence*100:confidence).toFixed(0)}%":"—"; el.inundCopy.textContent=data?.message||"Inundation model output returned for the selected station/location."; el.inundMapLabel.textContent=data?.map_url?"MODEL MAP AVAILABLE":"MODEL OUTPUT"; return true;
}
async function fetchEngine(path,r){ try{const params=new URLSearchParams({station:r.station||"",district:r.district||"",river:r.river||""});const res=await fetch(`${API_BASE}/${path}?${params}`,{headers:{Accept:"application/json"}});if(!res.ok)return null;const p=await res.json();return p?.success===false?null:p;}catch{return null;} }
async function loadEngines(r){ resetEnginePanels(); if(!r)return; el.riskFactLevel.textContent=`${fmt(r.water_level_m)} m`;const change=Number(r.water_level_m)-Number(r.water_level_1h_before_m);el.riskFactRise.textContent=Number.isFinite(change)?`${change>=0?"+":""}${change.toFixed(2)} m`:`${String(r.trend||"—")}`;el.riskFactState.textContent=statusLabel(levelStatus(r));
  const [risk, inund]=await Promise.all([fetchEngine("risk",r),fetchEngine("flood-risk",r)]);
  if(!risk) el.riskEngineState.textContent="UI ready • endpoint pending"; else riskFromApi(risk,r);
  if(!inund) {const alt=await fetchEngine("inundation",r);if(!alt) {el.inundationBadge.textContent="ENGINE READY";el.inundationBadge.className="engine-state advisory";el.inundationLabel.textContent="AWAITING MODEL";el.inundationLabel.className="engine-state advisory";el.inundationCopy.textContent="Inundation UI is ready; connect the terrain/hydrology/flood-extent prediction endpoint when the model is implemented.";} else inundationFromApi(alt);} else inundationFromApi(inund);
}
function select(r){ selectedStation=r; const s=levelStatus(r); el.detailStation.textContent=r.station||"Unknown station";el.detailRiver.textContent=`${r.river||"River"} • ${r.district||"Bihar"}`;el.detailStatus.textContent=statusLabel(s);el.detailStatus.className=`detail-status ${s}`;el.detailLevel.textContent=fmt(r.water_level_m);el.detailWarning.textContent=`${fmt(r.warning_level_m)} m`;el.detailDanger.textContent=`${fmt(r.danger_level_m)} m`;el.detailHfl.textContent=`${fmt(r.hfl_m)} m`;const change=Number(r.water_level_m)-Number(r.water_level_1h_before_m);el.detailChange.textContent=Number.isFinite(change)?`${change>=0?"+":""}${change.toFixed(2)} m`:"—";el.detailTrend.textContent=r.trend||"—";el.detailObserved.textContent=observed(r.observed_at);const w=Number(r.warning_level_m),d=Number(r.danger_level_m),h=Number(r.hfl_m),l=Number(r.water_level_m),max=Number.isFinite(h)&&h>0?h:Math.max(w,d,l,1),pos=v=>`${Math.max(0,Math.min(100,v/max*100))}%`;el.warningMarker.style.left=Number.isFinite(w)?pos(w):"0%";el.dangerMarker.style.left=Number.isFinite(d)?pos(d):"0%";el.levelMarker.style.left=Number.isFinite(l)?pos(l):"0%";el.levelMarker.className=`level-marker ${s}`;render();loadEngines(r); }
async function load(force=false){ el.error.hidden=true;apiState(false,"LOADING");el.refresh.disabled=true;el.table.innerHTML='<tr><td colspan="6" class="empty-state">Loading river intelligence...</td></tr>';try{const q=force?"?refresh=true":"",res=await fetch(`${API_BASE}/live-rivers${q}`,{headers:{Accept:"application/json"}}),p=await res.json();if(!res.ok||!p.success)throw new Error(p.error||`API request failed (${res.status})`);records=Array.isArray(p.records)?p.records:[];districts();const mode=p.source_mode==="neon_live_snapshot"?"LIVE • Neon synced":p.cached?"cached":"fresh";const when=p.fetched_at?observed(p.fetched_at):"unknown";el.meta.textContent=`${mode} • last sync ${when} • ${p.count??records.length} stations`;alertState();render();if(!selectedStation&&records.length)select(records[0]);else if(selectedStation){const current=records.find(r=>r.station===selectedStation.station&&r.district===selectedStation.district);if(current)select(current);}apiState(true,p.source_mode==="neon_live_snapshot"?"API ONLINE · LIVE SYNC":"API ONLINE");}catch(e){records=[];metrics([]);el.table.innerHTML='<tr><td colspan="6" class="empty-state">Live observations could not be loaded.</td></tr>';el.meta.textContent="Live data unavailable";el.error.hidden=false;el.errorText.textContent=e instanceof Error?e.message:"Unable to fetch live Bihar river data.";apiState(false,"API OFFLINE");resetEnginePanels();}finally{el.refresh.disabled=false;}}
el.search.addEventListener("input",render);el.district.addEventListener("change",e=>{selectedDistrict=e.target.value;render();});el.level.addEventListener("change",e=>{selectedLevel=e.target.value;render();});el.refresh.addEventListener("click",()=>load(true));load();setInterval(()=>load(false),60000);